#import "./fragments.graphql"

query AllFaqs {
  allFaqs(first: 100) {
    _createdAt
    _updatedAt
    id
    title
    slug
    customUpdateDate
    nascondiValutazione
    idAvvisoSalesforce
    seo: _seoMetaTags {
      attributes
      content
      tag
    }
    category {
      label
      slug
    }
    beneficiari {
      label
    }
    misura {
      label
      slug
      basePath
    }
    body {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on SplitBannerRecord {
        ...SplitBannerFragment
      }
      ... on BannerRecord {
        ...BannerFragment
      }
      ... on RichTextSectionRecord {
        ...RichTextSectionFragment
      }
      ... on VideoPlayerRecord {
        ...VideoPlayerFragment
      }
      ... on CardsGridGenericRecord {
        ...CardsGridGenericFragment
      }
      ... on CardsGridAttachmentRecord {
        ...CardsGridAttachmentFragment
      }
      ... on CardsGridServiceRecord {
        ...CardsGridServiceFragment
      }
      ... on CardsGridNewsRecord {
        ...CardsGridNewsFragment
      }
      ... on CardsGridResourceRecord {
        ...CardsGridResourceFragment
      }
      ... on CardsGridAnnouncementRecord {
        ...CardsGridAnnouncementFragment
      }
      ... on CardsGridImageRecord {
        ...CardsGridImagesFragment
      }
      ... on LayoutSidebarRecord {
        ...LayoutSidebarFragment
      }
      ... on LayoutSidebarFilterRecord {
        ...LayoutSidebarFilterFragment
      }
      ... on TableListRecord {
        ...TableListFragment
      }
      ... on TableListFaqRecord {
        ...TableListFaqFragment
      }
      ... on TableListUpdateRecord {
        ...TableListUpdateFragment
      }
    }
  }
  _allFaqsMeta {
    count
  }
}
