#import "./fragments.graphql"

query AllNews {
  allNews(first: 100) {
    _createdAt
    _updatedAt
    title
    slug
    customUpdateDate
    body {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on DataHeroRecord {
        ...DataHeroFragment
      }
      ... on SplitBannerRecord {
        ...SplitBannerFragment
      }
      ... on BannerRecord {
        ...BannerFragment
      }
      ... on RichTextSectionRecord {
        ...RichTextSectionFragment
      }
      ... on VideoPlayerRecord {
        ...VideoPlayerFragment
      }
      ... on CardsGridGenericRecord {
        ...CardsGridGenericFragment
      }
      ... on CardsGridAttachmentRecord {
        ...CardsGridAttachmentFragment
      }
      ... on CardsGridServiceRecord {
        ...CardsGridServiceFragment
      }
      ... on CardsGridNewsRecord {
        ...CardsGridNewsFragment
      }
      ... on CardsGridResourceRecord {
        ...CardsGridResourceFragment
      }
      ... on CardsGridAnnouncementRecord {
        ...CardsGridAnnouncementFragment
      }
      ... on CardsGridImageRecord {
        ...CardsGridImagesFragment
      }
      ... on LayoutSidebarRecord {
        ...LayoutSidebarFragment
      }
    }
  }
  _allNewsMeta {
    count
  }
}
