#import "./fragments.graphql"

query AllPages {
  allPages(first: 100) {
    _createdAt
    _updatedAt
    id
    title
    slug
    customUpdateDate
    body {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on SplitBannerRecord {
        ...SplitBannerFragment
      }
      ... on BannerRecord {
        ...BannerFragment
      }
      ... on RichTextSectionRecord {
        ...RichTextSectionFragment
      }
      ... on VideoPlayerRecord {
        ...VideoPlayerFragment
      }
      ... on CardsGridGenericRecord {
        ...CardsGridGenericFragment
      }
      ... on CardsGridAttachmentRecord {
        ...CardsGridAttachmentFragment
      }
      ... on CardsGridServiceRecord {
        ...CardsGridServiceFragment
      }
      ... on CardsGridNewsRecord {
        ...CardsGridNewsFragment
      }
      ... on CardsGridResourceRecord {
        ...CardsGridResourceFragment
      }
      ... on CardsGridAnnouncementRecord {
        ...CardsGridAnnouncementFragment
      }
      ... on CardsGridImageRecord {
        ...CardsGridImagesFragment
      }
      ... on LayoutSidebarRecord {
        ...LayoutSidebarFragment
      }
      ... on LayoutSidebarFilterRecord {
        ...LayoutSidebarFilterFragment
      }
      ... on TableListRecord {
        ...TableListFragment
      }
      ... on TableListFaqRecord {
        ...TableListFaqFragment
      }
      ... on TableListUpdateRecord {
        ...TableListUpdateFragment
      }
      ... on CardsListFilterRecord {
        ...CardsListFilterFragment
      }
      ... on HeroSearchRecord {
        ...HeroSearchFragment
      }
      ... on InstantSearchFaqRecord {
        ...InstantSearchFaqFragment
      }
      ... on BloccoGraficoRecord {
        ...BloccoGraficoFragment
      }
      ... on TabsWrapRecord {
        ...TabsWrapFragment
      }
    }
  }
  _allPagesMeta {
    count
  }
}
