#import "./fragments.graphql"

query AllPages {
  allPages(first: 100) {
    title
    slug
    customUpdateDate
    body {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on DataHeroRecord {
        ...DataHeroFragment
      }
      ... on SplitBannerRecord {
        ...SplitBannerFragment
      }
      ... on BannerRecord {
        ...BannerFragment
      }
      ... on RichTextRecord {
        ...RichTextFragment
      }
      ... on VideoPlayerRecord {
        ...VideoPlayerFragment
      }
      ... on CardServiceRecord {
        __typename
        id
        title
      }
      ... on CardsGridRecord {
        ...CardsGridFragment
      }
      ... on LayoutSidebarRecord {
        ...LayoutSidebarFragment
      }
    }
  }
  _allPagesMeta {
    count
  }
}
