#import "./fragments.graphql"

query AllResources {
  allResources(first: 100) {
    title
    slug
    customUpdateDate
    body {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on DataHeroRecord {
        ...DataHeroFragment
      }
      ... on SplitBannerRecord {
        ...SplitBannerFragment
      }
      ... on BannerRecord {
        ...BannerFragment
      }
      ... on RichTextRecord {
        ...RichTextFragment
      }
      ... on VideoPlayerRecord {
        ...VideoPlayerFragment
      }
      ... on CardsGridRecord {
        ...CardsGridFragment
      }
      ... on CardsGridGenericRecord {
        ...CardsGridGenericFragment
      }
      ... on CardsGridAttachmentRecord {
        ...CardsGridAttachmentFragment
      }
      ... on CardsGridServiceRecord {
        ...CardsGridServiceFragment
      }
      ... on CardsGridNewsRecord {
        ...CardsGridNewsFragment
      }
      ... on CardsGridResourceRecord {
        ...CardsGridResourceFragment
      }
      ... on LayoutSidebarRecord {
        ...LayoutSidebarFragment
      }
    }
  }
  _allResourcesMeta {
    count
  }
}
