#import "./fragments.graphql"

query allSupportos {
  allSupportos(first: 100) {
    _createdAt
    _updatedAt
    id
    title
    slug
    nascondiValutazione
    seo: _seoMetaTags {
      attributes
      content
      tag
    }
    body {
      ... on HeroRecord {
        ...HeroFragment
      }
      ... on SplitBannerRecord {
        ...SplitBannerFragment
      }
      ... on BannerRecord {
        ...BannerFragment
      }
      ... on RichTextSectionRecord {
        ...RichTextSectionFragment
      }
      ... on VideoPlayerRecord {
        ...VideoPlayerFragment
      }
      ... on CardsGridGenericRecord {
        ...CardsGridGenericFragment
      }
      ... on CardsGridAttachmentRecord {
        ...CardsGridAttachmentFragment
      }
      ... on CardsGridServiceRecord {
        ...CardsGridServiceFragment
      }
      ... on CardsGridNewsRecord {
        ...CardsGridNewsFragment
      }
      ... on CardsGridResourceRecord {
        ...CardsGridResourceFragment
      }
      ... on CardsGridAnnouncementRecord {
        ...CardsGridAnnouncementFragment
      }
      ... on CardsGridImageRecord {
        ...CardsGridImagesFragment
      }
      ... on LayoutSidebarRecord {
        ...LayoutSidebarFragment
      }
      ... on LayoutSidebarFilterRecord {
        ...LayoutSidebarFilterFragment
      }
      ... on TableListRecord {
        ...TableListFragment
      }
      ... on FormToRecord {
        ...FormToFragment
      }
      ... on FormAssistanceRecord {
        ...FormAssistanceFragment
      }
    }
  }
  _allPagesMeta {
    count
  }
}
