query Footer {
  footer {
    title
    titleColonna1
    linkColonna1 {
      ... on PageRecord {
        id
        slug
        title
      }
      ... on NewsRecord {
        id
        slug
        title
      }
      ... on ResourceRecord {
        id
        slug
        title
      }
      ... on FaqRecord {
        id
        slug
        title
      }
      ... on SupportoRecord {
        id
        slug
        title
      }
    }
    titleColonna2
    linkColonna2 {
      ... on PageRecord {
        id
        slug
        title
      }
      ... on NewsRecord {
        id
        slug
        title
      }
      ... on ResourceRecord {
        id
        slug
        title
      }
      ... on FaqRecord {
        id
        slug
        title
      }
      ... on SupportoRecord {
        id
        slug
        title
      }
    }
    titleColonna3
    linkColonna3 {
      ... on PageRecord {
        id
        slug
        title
      }
      ... on NewsRecord {
        id
        slug
        title
      }
      ... on ResourceRecord {
        id
        slug
        title
      }
      ... on FaqRecord {
        id
        slug
        title
      }
      ... on SupportoRecord {
        id
        slug
        title
      }
    }
    linkNewsletter {
      ... on PageRecord {
        id
        slug
        title
      }
      ... on NewsRecord {
        id
        slug
        title
      }
      ... on ResourceRecord {
        id
        slug
        title
      }
      ... on FaqRecord {
        id
        slug
        title
      }
      ... on SupportoRecord {
        id
        slug
        title
      }
    }
    linkUtili {
      ... on PageRecord {
        id
        slug
        title
      }
      ... on NewsRecord {
        id
        slug
        title
      }
      ... on ResourceRecord {
        id
        slug
        title
      }
      ... on FaqRecord {
        id
        slug
        title
      }
      ... on SupportoRecord {
        id
        slug
        title
      }
    }
  }
}
