fragment CardsGridFieldsetFragment on CardsGridFieldsetRecord {
  __typename
  id
  title
  titleHtmlTag
  description
  alignment
  columns
  singleCardsTitleTag
  button {
    ... ButtonFragment
  }
  backgroundColor
}

fragment ButtonFragment on ButtonRecord {
  __typename
  id
  href
  target
  text
  icon
  cmsPage {
    title
    slug
    id
  }
}

fragment ImageFragment on ResponsiveImage {
  __typename
  src
  alt
  aspectRatio
  width
  height
}

fragment ImagesGridFragment on ImagesGridRecord {
  __typename
  id
  images {
    url
    basename
    alt
    format
    width
    height
    id
    title
    responsiveImage {
      ...ImageFragment
    }
  }
}

fragment LinkFragment on LinkRecord {
  __typename
  id
  href
  icon
  target
  text
  cmsPage {
    slug
    title
    id
  }
}

fragment RichTextContentFragment on RichTextModelContentBlocksField {
  ... on ImagesGridRecord {
    ...ImagesGridFragment
  }
  ... on LinkRecord {
    ...LinkFragment
  }
  ... on ButtonRecord {
    ...ButtonFragment
  }
  ... on VideoPlayerRecord {
    ...VideoPlayerFragment
  }
  ... on CardsGridRecord {
    ...CardsGridFragment
  }
  ... on CardsGridGenericRecord {
    ...CardsGridGenericFragment
  }
  ... on CardsGridAttachmentRecord {
    ...CardsGridAttachmentFragment
  }
  ... on CardsGridServiceRecord {
    ...CardsGridServiceFragment
  }
  ... on CardsGridNewsRecord {
    ...CardsGridNewsFragment
  }
  ... on CardsGridResourceRecord {
    ...CardsGridResourceFragment
  }
  ... on CardsGridAnnouncementRecord {
    ...CardsGridAnnouncementFragment
  }
}

fragment RichTextSectionFragment on RichTextSectionRecord {
  __typename
  alignment
  richTextContent: content {
    value
    blocks {
      ...RichTextContentFragment
    }
  }
}

fragment LayoutSidebarFragment on LayoutSidebarRecord {
  __typename
  sidebar {
    ...NavScrollFragment
  }
  content {
    alignment
    anchorId
    richTextContent: content {
      value
      blocks {
        ...RichTextContentFragment
      }
    }
  }
}

fragment VideoPlayerFragment on VideoPlayerRecord {
  __typename
  id
  title
  transcription
  transcriptionLabel
  videoSources {
    sourceSrc
    sourceType
  }
  poster {
    url
  }
}

fragment NavScrollFragment on NavScrollRecord {
  __typename
  title
  content {
    value
  }
}
fragment CardsGridFragment on CardsGridRecord {
  __typename
}
fragment HeroFragment on HeroRecord {
  __typename
  lightTheme
  hideBreadcrumbs
  title
  description
  updateDate
  image {
    responsiveImage {
      ...ImageFragment
    }
  }
  button {
    ...ButtonFragment
  }
}

fragment DataHeroFragment on DataHeroRecord {
  __typename
  hideBreadcrumbs
  title
  updateDate
  button {
    ...ButtonFragment
  }
  argomento {
    label
    slug
  }
  badge {
    label
  }
  beneficiari {
    label
  }
  misura {
    label
    slug
    basePath
  }
}

fragment SplitBannerFragment on SplitBannerRecord {
  __typename
  id
  title
  description
  imgLeft
  lightTheme
  links {
    id
    slug
    title
  }
  image {
    responsiveImage {
      ...ImageFragment
    }
  }
  button {
    ...ButtonFragment
  }
}

fragment BannerFragment on BannerRecord {
  __typename
  id
  title
  description
  lightTheme
  button {
    ...ButtonFragment
  }
}

fragment TableListItemFragment on TableListItemRecord {
  __typename
  date
  title
  link {
    ...LinkFragment
  }
}

fragment TableListLinkItemFragment on TableListLinkItemRecord {
  __typename
  category {
    label
    slug
  }
  link {
    __typename
    id
    href
    icon
    target
    text
    cmsPage {
      slug
      title
      id
      body {
        __typename
        ... on DataHeroRecord {
          id
          badge {
            label
          }
        }
      }
    }
  }
}

fragment TableListFragment on TableListRecord {
  __typename
  id
  title
  showTableHead
  alignment
  button {
    ...ButtonFragment
  }
  items {
    ... on TableListItemRecord {
      ...TableListItemFragment
    }
    ... on TableListLinkItemRecord {
      ...TableListLinkItemFragment
    }
  }
}

fragment CardsGridGenericFragment on CardsGridGenericRecord {
  __typename
  id
  sectionFields {
    ... CardsGridFieldsetFragment
  }
  cardLayout
  cards {
    ... on CardGenericRecord {
      __typename
      id
      title
      description
      date
      label
      iconBeforeTitle
      href
      cmsPage {
        title
        slug
      }
      target
    }
  }
}


fragment CardsGridAttachmentFragment on CardsGridAttachmentRecord {
  __typename
  id
  sectionFields {
    ... CardsGridFieldsetFragment
  }
  cards {
    ... on CardAttachmentRecord {
      __typename
      id
      title
      description
      date
      label
      href
      cmsAsset {
        title
        url
      }
      target
      badge
    }
  }
}

fragment CardsGridServiceFragment on CardsGridServiceRecord {
  __typename
  id
  sectionFields {
    ... CardsGridFieldsetFragment
  }
  cards {
    ... on CardServiceRecord {
      __typename
      id
      title
      description
      label
      button {
        __typename
        id
        href
        target
        text
        icon
        cmsPage {
          title
          slug
        }
      }
    }
  }
}



fragment CardsGridNewsFragment on CardsGridNewsRecord {
  __typename
  id
  sectionFields {
    ... CardsGridFieldsetFragment
  }
  news {
    __typename
    id
    slug
    title
    summary
    category
    data
  }
}


fragment CardsGridResourceFragment on CardsGridResourceRecord {
  __typename
  id
  sectionFields {
    ... CardsGridFieldsetFragment
  }
  resources {
    __typename
    id
    slug
    title
    summary
    badge
    data
  }
}

fragment CardsGridAnnouncementFragment on CardsGridAnnouncementRecord {
  __typename
  id
  sectionFields {
    ... CardsGridFieldsetFragment
  }
}
