fragment CardsGridFieldsetFragment on CardsGridFieldsetRecord {
  __typename
  id
  title
  titleHtmlTag
  description
  alignment
  columns
  singleCardsTitleTag
  button {
    ...ButtonFragment
  }
  backgroundColor
}

fragment ButtonFragment on ButtonRecord {
  __typename
  id
  href
  target
  text
  icon
  cmsPage {
    ... on PageRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on NewsRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on ResourceRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on FaqRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on SupportoRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
  }
}

fragment ImageFragment on ResponsiveImage {
  __typename
  src
  alt
  aspectRatio
  width
  height
}

fragment ImagesGridFragment on ImagesGridRecord {
  __typename
  id
  images {
    url
    basename
    alt
    format
    width
    height
    id
    title
    responsiveImage {
      ...ImageFragment
    }
  }
}

fragment LinkFragment on LinkRecord {
  __typename
  id
  href
  icon
  target
  text
  cmsPage {
    ... on PageRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on NewsRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on ResourceRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on FaqRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
    ... on SupportoRecord {
      __typename
      _createdAt
      _updatedAt
      title
      slug
      id
    }
  }
}

fragment RichTextContentFragment on RichTextModelContentBlocksField {
  ... on ImagesGridRecord {
    ...ImagesGridFragment
  }
  ... on LinkRecord {
    ...LinkFragment
  }
  ... on ButtonRecord {
    ...ButtonFragment
  }
  ... on VideoPlayerRecord {
    ...VideoPlayerFragment
  }
  ... on CardsGridRecord {
    ...CardsGridFragment
  }
  ... on CardsGridGenericRecord {
    ...CardsGridGenericFragment
  }
  ... on CardsGridAttachmentRecord {
    ...CardsGridAttachmentFragment
  }
  ... on CardsGridServiceRecord {
    ...CardsGridServiceFragment
  }
  ... on CardsGridNewsRecord {
    ...CardsGridNewsFragment
  }
  ... on CardsGridResourceRecord {
    ...CardsGridResourceFragment
  }
  ... on CardsGridAnnouncementRecord {
    ...CardsGridAnnouncementFragment
  }
  ... on CardsGridImageRecord {
    ...CardsGridImagesFragment
  }
  ... on TableListRecord {
    ...TableListFragment
  }
  ... on TableListFaqRecord {
    ...TableListFaqFragment
  }
  ... on TableListUpdateRecord {
    ...TableListUpdateFragment
  }
}

fragment RichTextSectionFragment on RichTextSectionRecord {
  __typename
  alignment
  richTextContent: content {
    value
    blocks {
      ...RichTextContentFragment
      ... on StepperRecord {
        ...StepperFragment
      }
    }
  }
}

fragment LayoutSidebarFragment on LayoutSidebarRecord {
  __typename
  sidebar {
    ...NavScrollFragment
  }
  content {
    ... on RichTextRecord {
      __typename
      id
      alignment
      anchorId
      richTextContent: content {
        value
        blocks {
          ...RichTextContentFragment
        }
      }
    }
    ... on StepperRecord {
      ...StepperFragment
    }
  }
}

fragment LayoutSidebarFilterFragment on LayoutSidebarFilterRecord {
  __typename
  sidebar {
    ...NavScrollFragment
  }
  content {
    ... on RichTextRecord {
      __typename
      id
      alignment
      anchorId
      richTextContent: content {
        value
        blocks {
          ...RichTextContentFragment
        }
      }
    }
    ... on StepperRecord {
      ...StepperFragment
    }
  }
}

fragment VideoPlayerFragment on VideoPlayerRecord {
  __typename
  id
  title
  transcription
  transcriptionLabel
  videoSources {
    sourceSrc
    sourceType
  }
  poster {
    url
  }
}

fragment NavScrollFragment on NavScrollRecord {
  __typename
  title
  content {
    value
  }
}
fragment CardsGridFragment on CardsGridRecord {
  __typename
}
fragment HeroFragment on HeroRecord {
  __typename
  lightTheme
  hideBreadcrumbs
  title
  description
  updateDate
  image {
    responsiveImage {
      ...ImageFragment
    }
  }
  button {
    ...ButtonFragment
  }
}

fragment DataHeroFragment on DataHeroRecord {
  __typename
  hideBreadcrumbs
  title
  updateDate
  argomento {
    label
    slug
  }
  beneficiari {
    label
  }
  misura {
    label
    slug
    basePath
  }
}

fragment SplitBannerFragment on SplitBannerRecord {
  __typename
  id
  title
  description
  imgLeft
  lightTheme
  links {
    id
    slug
    title
  }
  image {
    responsiveImage {
      ...ImageFragment
    }
  }
  button {
    ...ButtonFragment
  }
}

fragment BannerFragment on BannerRecord {
  __typename
  id
  title
  description
  lightTheme
  button {
    ...ButtonFragment
  }
}

fragment TableListItemFragment on TableListItemRecord {
  __typename
  date
  title
  link {
    ...LinkFragment
  }
}

fragment TableListLinkItemFragment on TableListLinkItemRecord {
  __typename
  category {
    label
    slug
  }
  link {
    ...LinkFragment
  }
}

fragment TableListFragment on TableListRecord {
  __typename
  id
  title
  showTableHead
  alignment
  button {
    ...ButtonFragment
  }
  items {
    ... on TableListItemRecord {
      ...TableListItemFragment
    }
    ... on TableListLinkItemRecord {
      ...TableListLinkItemFragment
    }
  }
}

fragment CardsGridGenericFragment on CardsGridGenericRecord {
  __typename
  id
  sectionFields {
    ...CardsGridFieldsetFragment
  }
  cardLayout
  cards {
    ... on CardGenericRecord {
      __typename
      id
      title
      description
      date
      label
      iconBeforeTitle
      iconAfterTitle
      href
      cmsPage {
        title
        slug
      }
      target
    }
  }
}

fragment CardAttachmentFragment on CardAttachmentRecord {
  __typename
  id
  title
  description
  date
  label
  href
  cmsAsset {
    title
    url
  }
  target
  badge
}

fragment CardsGridAttachmentFragment on CardsGridAttachmentRecord {
  __typename
  id
  sectionFields {
    ...CardsGridFieldsetFragment
  }
  cards {
    ... on CardAttachmentRecord {
      ...CardAttachmentFragment
    }
  }
}

fragment CardsGridServiceFragment on CardsGridServiceRecord {
  __typename
  id
  sectionFields {
    ...CardsGridFieldsetFragment
  }
  cards {
    ... on CardServiceRecord {
      __typename
      id
      title
      description
      label
      button {
        ...ButtonFragment
      }
    }
  }
}

fragment CardsGridNewsFragment on CardsGridNewsRecord {
  __typename
  id
  sectionFields {
    ...CardsGridFieldsetFragment
  }
  newsSelection
  news {
    __typename
    id
    slug
    externalLink
    title
    summary
    category
    customUpdateDate
  }
}

fragment CardsGridResourceFragment on CardsGridResourceRecord {
  __typename
  id
  sectionFields {
    ...CardsGridFieldsetFragment
  }
  resources {
    __typename
    _createdAt
    _updatedAt
    id
    slug
    title
    summary
    data
  }
}

fragment CardsGridAnnouncementFragment on CardsGridAnnouncementRecord {
  __typename
  id
  borderOnTop
  sectionFields {
    ...CardsGridFieldsetFragment
  }
}

fragment CardImageFragment on CardImageRecord {
  __typename
  id
  didascalia
  image {
    id
    __typename
    size
    alt
    height
    width
    url1_1: url(imgixParams: { w: 1280, h: 1280, fit: crop, fm: webp })
    url21_9: url(imgixParams: { w: 1281, h: 549, fit: crop, fm: webp })
    url16_9: url(imgixParams: { w: 1280, h: 720, fit: crop, fm: webp })
    url4_3: url(imgixParams: { w: 1280, h: 960, fit: crop, fm: webp })
    url32_9: url(imgixParams: { w: 1280, h: 360, fit: crop, fm: webp })
    url7_11: url(imgixParams: { w: 819, h: 1287, fit: crop, fm: webp })
    title
  }
  href
  cmsPage {
    title
    slug
  }
  target
}

fragment CardsGridImagesFragment on CardsGridImageRecord {
  __typename
  id
  title
  titleHtmlTag
  description
  alignment
  captions
  layout
  button {
    ...ButtonFragment
  }
  backgroundColor
  imageBlocks: images {
    ... on CardImageRecord {
      ...CardImageFragment
    }
  }
}

fragment StepperFragment on StepperRecord {
  __typename
  id
  anchorId
  layout
  steps {
    ... on StepperStepRecord {
      __typename
      id
      stepTitle
      stepStatus
      stepBody {
        ... on RichTextStepperRecord {
          __typename
          id
          alignment
          content {
            ... on RichTextStepperModelContentField {
              __typename
              value
              blocks {
                ... on LinkRecord {
                  ...LinkFragment
                }
                ... on ButtonRecord {
                  ...ButtonFragment
                }
                ... on CardAttachmentRecord {
                  ...CardAttachmentFragment
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment TableListFaqFragment on TableListFaqRecord {
  __typename
  id
  questionsRef {
    _createdAt
    _updatedAt
    slug
    title
    category {
      label
    }
    beneficiari {
      id
      label
    }
  }
}

fragment AccordionsFilterFragment on AccordionsFilterRecord {
  __typename
  id
  items {
    __typename
    id
    titleMisura {
      id
      label
      slug
    }
    resources {
      __typename
      _createdAt
      _updatedAt
      id
      slug
      title
      summary
      data
      entiBeneficiari {
        id
        label
      }
    }
  }
}

fragment TableListUpdateFragment on TableListUpdateRecord {
  __typename
  id
  title
  alignment
  showLastItems
  filterByInstitute {
    __typename
    id
    label
  }
  button {
    ...ButtonFragment
  }
}

fragment CardMisuraFragment on CardMisuraRecord {
  __typename
  id
  title
  misura {
    id
    label
  }
  entePromotore {
    id
    label
  }
  entiBeneficiari {
    id
    label
  }
}

fragment CardsListFilterFragment on CardsListFilterRecord {
  __typename
  id
  items {
    ...CardMisuraFragment
  }
}
