fragment ButtonFragment on ButtonRecord {
  __typename
  id
  href
  target
  text
  icon
  cmsPage {
    title
    slug
    id
  }
}

fragment ImageFragment on ResponsiveImage {
  __typename
  src
  alt
  aspectRatio
  width
  height
}

fragment ImagesGridFragment on ImagesGridRecord {
  __typename
  id
  images {
    url
    basename
    alt
    format
    width
    height
    id
    title
    responsiveImage {
      ...ImageFragment
    }
  }
}

fragment LinkFragment on LinkRecord {
  __typename
  id
  href
  icon
  target
  text
  cmsPage {
    slug
    title
    id
  }
}

fragment RichTextContentFragment on RichTextModelContentBlocksField {
  ... on ImagesGridRecord {
    ...ImagesGridFragment
  }
  ... on LinkRecord {
    ...LinkFragment
  }
  ... on ButtonRecord {
    ...ButtonFragment
  }
  ... on VideoPlayerRecord {
    ...VideoPlayerFragment
  }
  ... on CardsGridRecord {
    ...CardsGridFragment
  }
}

fragment RichTextFragment on RichTextRecord {
  __typename
  alignment
  anchorId
  richTextContent: content {
    value
    blocks {
      ...RichTextContentFragment
    }
  }
}

fragment LayoutSidebarFragment on LayoutSidebarRecord {
  __typename
  sidebar {
    ...NavScrollFragment
  }
  content {
    alignment
    anchorId
    richTextContent: content {
      value
      blocks {
        ...RichTextContentFragment
      }
    }
  }
}

fragment VideoPlayerFragment on VideoPlayerRecord {
  __typename
  id
  title
  transcription
  transcriptionLabel
  videoSources {
    sourceSrc
    sourceType
  }
  poster {
    url
  }
}

fragment NavScrollFragment on NavScrollRecord {
  __typename
  title
  content {
    value
  }
}

fragment CardsGridFragment on CardsGridRecord {
  __typename
  id
  background
  title
  description
  alignment
  columns
  cardTitleTag
  customCards {
    __typename
    id
    cardLayout
    cards {
      ... on CardGenericRecord {
        __typename
        id
        title
        description
        date
        label
        iconBeforeTitle
        href
        cmsPage {
          title
          slug
        }
        target
      }
      ... on CardAttachmentRecord {
        __typename
        id
        title
        description
        date
        label
        href
        cmsAsset {
          alt
          basename
          filename
          mimeType
          size
          url
          title
        }
        target
        updated
      }
    }
  }
  risorse {
    __typename
    id
    slug
    title
    summary
    badge
    data
  }
  news {
    __typename
    id
    slug
    title
    summary
    category
    data
  }
  button {
    ...ButtonFragment
  }
}

fragment HeroFragment on HeroRecord {
  __typename
  lightTheme
  hideBreadcrumbs
  title
  description
  updateDate
  image {
    responsiveImage {
      ...ImageFragment
    }
  }
  button {
    ...ButtonFragment
  }
}

fragment DataHeroFragment on DataHeroRecord {
  __typename
  hideBreadcrumbs
  title
  updateDate
  button {
    ...ButtonFragment
  }
  argomento {
    label
    slug
  }
  badge {
    label
  }
  beneficiari {
    label
  }
  misura {
    label
    slug
    basePath
  }
}

fragment SplitBannerFragment on SplitBannerRecord {
  __typename
  id
  title
  description
  imgLeft
  lightTheme
  links {
    id
    slug
    title
  }
  image {
    responsiveImage {
      ...ImageFragment
    }
  }
  button {
    ...ButtonFragment
  }
}

fragment BannerFragment on BannerRecord {
  __typename
  id
  title
  description
  lightTheme
  button {
    ...ButtonFragment
  }
}

fragment TableListItemFragment on TableListItemRecord {
  __typename
  date
  title
  link {
    ...LinkFragment
  }
}

fragment TableListLinkItemFragment on TableListLinkItemRecord {
  __typename
  category {
    label
    slug
  }
  link {
    __typename
    id
    href
    icon
    target
    text
    cmsPage {
      slug
      title
      id
      body {
        __typename
        ... on DataHeroRecord {
          id
          badge {
            label
          }
        }
      }
    }
  }
}

fragment TableListFragment on TableListRecord {
  __typename
  id
  title
  showTableHead
  alignment
  button {
    ...ButtonFragment
  }
  items {
    ... on TableListItemRecord {
      ...TableListItemFragment
    }
    ... on TableListLinkItemRecord {
      ...TableListLinkItemFragment
    }
  }
}
