#import "./fragments.graphql"

query Guideline($id: ItemId) {
  guideline(filter: { id: { eq: $id } }) {
    __typename
    _createdAt
    _updatedAt
    id
    title
    descrizione
    customUpdateDate
    allegato {
      id
      size
      filename
      url
      format
    }
    idAvvisoSalesforce
    beneficiari {
      label
      id
      labelSalesforce
    }
    misura {
      label
      slug
      basePath
      idSalesforce
      pacchetto
    }
  }
  _allUpdatesMeta {
    count
  }
}
