#import "./fragments.graphql"

query Page($slug: String) {
  page(filter: {slug: {eq: $slug}}) {
    title
    slug
    customUpdateDate
    body {
      ... on HeroRecord {
        __typename
        lightTheme
        hideBreadcrumbs
        title
        description
        updateDate
        image {
          responsiveImage {
            ...ImageFragment
          }
        }
        button {
          ...ButtonFragment
        }
      }
      ... on DataHeroRecord {
        __typename
        hideBreadcrumbs
        title
        updateDate
        button {
          ...ButtonFragment
        }
        argomento {
          label
          slug
        }
        badge {
          label
        }
        beneficiari {
          label
        }
        misura {
          label
          slug
          basePath
        }
      }
      ... on SplitBannerRecord {
        __typename
        id
        title
        description
        imgLeft
        lightTheme
        links {
          id
          slug
          title
        }
        image {
          responsiveImage {
            ...ImageFragment
          }
        }
        button {
          ...ButtonFragment
        }
      }
      ... on BannerRecord {
        __typename
        id
        title
        description
        lightTheme
        button {
          ...ButtonFragment
        }
      }
      ... on RichTextRecord {
        __typename
        id
        alignment
        content {
          value
          blocks {
            ...RichTextContentFragment
          }
        }
      }
      ... on VideoPlayerRecord {
        __typename
        id
        title
        transcription
        transcriptionLabel
        videoSources {
          sourceSrc
          sourceType
        }
        poster {
          url
        }
      }
      ... on CardServiceRecord {
        __typename
        id
        title
      }
      ... on CardsGridRecord {
        ... CardsGridFragment
      }
    }
  }
}
