query Page($slug: String) {
  page(filter: { slug: { eq: $slug } }) {
    title
    slug
    body {
      ... on AlertRecord {
        __typename
        text
        color
      }
      ... on ButtonRecord {
        __typename
        text
        href
        cmsPage {
          slug
        }
        color
        target
        size
      }
      ... on HeroRecord {
        __typename
        lightTheme
        hideBreadcrumbs
        title
        description
        updateDate
        image {
          responsiveImage {
            __typename
            src
            alt
            aspectRatio
            width
            height
          }
        }
        button {
          id
          target
          href
          text
          color
          size
        }
      }
      ... on SplitBannerRecord {
        __typename
        id
        title
        description
        imgLeft
        lightTheme
        links
        image {
          responsiveImage {
            width
            title
            src
            alt
            aspectRatio
            height
            bgColor
            sizes
            srcSet
            webpSrcSet
          }
        }
        button {
          color
          href
          id
          size
          target
          text
        }
      }
    }
  }
}
