import type { Metadata } from "next";
import "./globals.css";

import "bootstrap-italia/dist/css/bootstrap-italia.min.css";

import "typeface-titillium-web";
import "typeface-roboto-mono";
import "typeface-lora";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
