import type { Metadata } from "next";
import Script from "next/script";

import "bootstrap-italia/dist/css/bootstrap-italia.min.css";
import "./globals.scss";

import "typeface-titillium-web";
import "typeface-roboto-mono";
import "typeface-lora";

import { getFooter, getHeader } from "@/lib/datocms";
import type { FooterQuery, HeaderQuery } from "@/graphql/generated";
import Header from "@/src/components/header";
import Footer from "@/src/components/footer";
import BootstrapInit from "@/src/components/BootstrapInit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const footerProps = (await getFooter()) as FooterQuery;
  const headerProps = (await getHeader()) as HeaderQuery;
  return (
    <html lang="it">
      <head>
        <Script
          src="/bootstrap-italia.bundle.min.js"
          strategy="afterInteractive"
        />
      </head>
      <body>
        <BootstrapInit />
        <Header props={headerProps} />
        <main id={"main"}>{children}</main>
        <Footer props={footerProps} />
      </body>
    </html>
  );
}
