query AlgoliaPage($id: ItemId) {
  page(filter: { id: { eq: $id } }) {
    id
    title
    slug
    body {
      ... on LayoutSidebarRecord {
        __typename
        ls_content: content {
          ... on RichTextRecord {
            __typename
            content {
              value
            }
          }
        }
      }
      ... on RichTextSectionRecord {
        __typename
        rt_content: content {
          value
        }
      }
      ... on HeroRecord {
        __typename
        title
        description
      }
      ... on BannerRecord {
        __typename
        title
        description
      }
      ... on CardsGridRecord {
        title
        description
      }
      ... on CardsGridGenericRecord {
        sectionFields {
          title
          description
        }
      }
      ... on CardsGridAttachmentRecord {
        sectionFields {
          title
          description
        }
      }
      ... on CardsGridServiceRecord {
        sectionFields {
          title
          description
        }
      }
      ... on CardsGridResourceRecord {
        sectionFields {
          title
          description
        }
      }
      ... on CardsGridNewsRecord {
        sectionFields {
          title
          description
        }
      }
      ... on CardsGridAnnouncementRecord {
        sectionFields {
          title
          description
        }
      }
      ... on CardsGridImageRecord {
        title
        description
        captions
      }
      ... on TableListRecord {
        title
      }
      ... on SplitBannerRecord {
        title
        description
      }
      ... on VideoPlayerRecord {
        title
        transcription
      }
      ... on TableListUpdateRecord {
        title
      }
    }
  }
}
